apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "phabrick.fullname" . }}
  labels:
    app: {{ template "phabrick.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  phabrick.yaml: |-
{{ .Values.phabrick | toYaml | indent 4 }}
