{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "phabrick.fullname" . }}
  labels:
    app: {{ template "phabrick.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  podSelector:
    matchLabels:
      app: {{ template "phabrick.name" . }}
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
{{- if .Values.networkPolicy.ingress }}
  ingress:
{{ toYaml .Values.networkPolicy.ingress | indent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
{{ toYaml .Values.networkPolicy.egress | indent 4 }}
  {{- end }}
{{- end }}